name: Release and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  publish-package:
    uses: yukiakai212/actions-public/.github/workflows/publish-package.yml@v1

    secrets: inherit